import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import { Toaster } from "@/components/ui/toaster";
import { GoogleOAuthProvider } from "@react-oauth/google";

export const metadata: Metadata = {
  icons: {
    icon: "/only-logo.svg",
  },
  title: "Travel AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased `}>
        <GoogleOAuthProvider
          clientId={process.env.NEXT_PUBLIC_GOOGLE_AUTH_CLIENT_ID!}
        >
          <Header />
          <Toaster />
          {children}
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
